apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-app
  namespace: devops
  

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-app

  template:
    metadata:
      labels:
        app: devops-app

    spec:
      containers:
      - name: devops-app

        image: image: 578339677090.dkr.ecr.us-east-1.amazonaws.com/devops-app:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"

          limits:
            memory: "512Mi"
            cpu: "500m"
