name: EKS-CICD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: vinod-eks-cluster
  ECR_REPOSITORY: devops-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Build Gradle App
      run: |
        cd app
        chmod +x gradlew
        ./gradlew build

    - name: Build Docker Image
      run: |
        docker build -t $ECR_REPOSITORY ./app

    - name: Tag Docker Image
      run: |
        docker tag $ECR_REPOSITORY:latest ${{ secrets.ECR_URI }}:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.ECR_URI }}:latest

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    - name: Replace Image URI
      run: |
        sed -i 's|YOUR_ECR_URI|${{ secrets.ECR_URI }}|g' kubernetes/deployment.yaml

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/
